<?php

namespace Database\Seeders;

use App\Models\SystemSetting;
use Illuminate\Database\Seeder;

class SystemSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // ========================================
            // POLICY & RISK MANAGEMENT
            // ========================================
            [
                'category' => SystemSetting::CATEGORY_POLICY_RISK,
                'key' => 'max_dti_ratio',
                'label' => 'Maximum Debt-to-Income Ratio',
                'value' => '45',
                'default_value' => '45',
                'data_type' => 'number',
                'unit' => '%',
                'description' => 'Maximum acceptable DTI ratio for loan approval',
                'validation_rules' => json_encode(['min' => 0, 'max' => 100]),
                'is_public' => true,
                'display_order' => 1,
            ],
            [
                'category' => SystemSetting::CATEGORY_POLICY_RISK,
                'key' => 'max_dsr_ratio',
                'label' => 'Maximum Debt Service Ratio',
                'value' => '40',
                'default_value' => '40',
                'data_type' => 'number',
                'unit' => '%',
                'description' => 'Maximum acceptable DSR ratio for loan approval',
                'validation_rules' => json_encode(['min' => 0, 'max' => 100]),
                'is_public' => true,
               'display_order' => 2,
            ],
            [
                'category' => SystemSetting::CATEGORY_POLICY_RISK,
                'key' => 'max_ltv_ratio',
                'label' => 'Maximum Loan-to-Value Ratio',
                'value' => '85',
                'default_value' => '85',
                'data_type' => 'number',
                'unit' => '%',
                'description' => 'Maximum LTV ratio for property-backed loans',
                'validation_rules' => json_encode(['min' => 0, 'max' => 100]),
                'is_public' => true,
                'display_order' => 3,
            ],
            [
                'category' => SystemSetting::CATEGORY_POLICY_RISK,
                'key' => 'min_loan_amount',
                'label' => 'Minimum Loan Amount',
                'value' => '1000000',
                'default_value' => '1000000',
                'data_type' => 'number',
                'unit' => 'TZS',
                'description' => 'Minimum loan amount that can be requested',
                'validation_rules' => json_encode(['min' => 0]),
                'is_public' => true,
                'display_order' => 4,
            ],
            [
                'category' => SystemSetting::CATEGORY_POLICY_RISK,
                'key' => 'max_loan_amount',
                'label' => 'Maximum Loan Amount',
                'value' => '500000000',
                'default_value' => '500000000',
                'data_type' => 'number',
                'unit' => 'TZS',
                'description' => 'Maximum loan amount that can be approved',
                'validation_rules' => json_encode(['min' => 0]),
                'is_public' => true,
                'display_order' => 5,
            ],
            [
                'category' => SystemSetting::CATEGORY_POLICY_RISK,
                'key' => 'min_tenure_months',
                'label' => 'Minimum Loan Tenure',
                'value' => '6',
                'default_value' => '6',
                'data_type' => 'number',
                'unit' => 'months',
                'description' => 'Minimum loan tenure in months',
                'validation_rules' => json_encode(['min' => 1]),
                'is_public' => true,
                'display_order' => 6,
            ],
            [
                'category' => SystemSetting::CATEGORY_POLICY_RISK,
                'key' => 'max_tenure_months',
                'label' => 'Maximum Loan Tenure',
                'value' => '300',
                'default_value' => '300',
                'data_type' => 'number',
                'unit' => 'months',
                'description' => 'Maximum loan tenure in months (25 years)',
                'validation_rules' => json_encode(['min' => 1]),
                'is_public' => true,
                'display_order' => 7,
            ],
            [
                'category' => SystemSetting::CATEGORY_POLICY_RISK,
                'key' => 'income_multiplier_salaried',
                'label' => 'Income Multiplier (Salaried)',
                'value' => '4',
                'default_value' => '4',
                'data_type' => 'number',
                'unit' => 'x',
                'description' => 'Maximum loan as multiple of annual income for salaried customers',
                'validation_rules' => json_encode(['min' => 0]),
                'is_public' => false,
                'display_order' => 8,
            ],
            [
                'category' => SystemSetting::CATEGORY_POLICY_RISK,
                'key' => 'income_multiplier_self_employed',
                'label' => 'Income Multiplier (Self-Employed)',
                'value' => '3',
                'default_value' => '3',
                'data_type' => 'number',
                'unit' => 'x',
                'description' => 'Maximum loan as multiple of annual income for self-employed customers',
                'validation_rules' => json_encode(['min' => 0]),
                'is_public' => false,
                'display_order' => 9,
            ],
            [
                'category' => SystemSetting::CATEGORY_POLICY_RISK,
                'key' => 'business_safety_factor',
                'label' => 'Business Safety Factor',
                'value' => '0.75',
                'default_value' => '0.75',
                'data_type' => 'number',
               'description' => 'Safety factor applied to self-employed income (0.75 = 75%)',
                'validation_rules' => json_encode(['min' => 0, 'max' => 1]),
                'is_public' => false,
                'display_order' => 10,
            ],

            // ========================================
            // INTEREST RATES & FEES
            // ========================================
            [
                'category' => SystemSetting::CATEGORY_INTEREST_RATES,
                'key' => 'default_interest_rate',
                'label' => 'Default Interest Rate',
                'value' => '15',
                'default_value' => '15',
                'data_type' => 'number',
                'unit' => '% p.a.',
                'description' => 'Default annual interest rate',
                'validation_rules' => json_encode(['min' => 0, 'max' => 100]),
                'is_public' => true,
                'display_order' => 1,
            ],
            [
                'category' => SystemSetting::CATEGORY_INTEREST_RATES,
                'key' => 'min_interest_rate',
                'label' => 'Minimum Interest Rate',
                'value' => '10',
                'default_value' => '10',
                'data_type' => 'number',
                'unit' => '% p.a.',
                'description' => 'Minimum allowable interest rate',
                'validation_rules' => json_encode(['min' => 0, 'max' => 100]),
                'is_public' => false,
                'display_order' => 2,
            ],
            [
                'category' => SystemSetting::CATEGORY_INTEREST_RATES,
                'key' => 'max_interest_rate',
                'label' => 'Maximum Interest Rate',
                'value' => '30',
                'default_value' => '30',
                'data_type' => 'number',
                'unit' => '% p.a.',
                'description' => 'Maximum allowable interest rate',
                'validation_rules' => json_encode(['min' => 0, 'max' => 100]),
                'is_public' => false,
                'display_order' => 3,
            ],
            [
                'category' => SystemSetting::CATEGORY_INTEREST_RATES,
                'key' => 'default_interest_method',
                'label' => 'Default Interest Calculation Method',
                'value' => 'reducing_balance',
                'default_value' => 'reducing_balance',
                'data_type' => 'string',
                'description' => 'Default method for interest calculation',
                'options' => json_encode(['flat_rate', 'reducing_balance', 'reducing_balance_equal_installments']),
                'validation_rules' => json_encode(['in' => ['flat_rate', 'reducing_balance', 'reducing_balance_equal_installments']]),
                'is_public' => true,
                'display_order' => 4,
            ],
            [
                'category' => SystemSetting::CATEGORY_INTEREST_RATES,
                'key' => 'late_payment_penalty_rate',
                'label' => 'Late Payment Penalty Rate',
                'value' => '5',
                'default_value' => '5',
                'data_type' => 'number',
                'unit' => '% per month',
                'description' => 'Penalty rate for late payments',
                'validation_rules' => json_encode(['min' => 0]),
                'is_public' => true,
                'display_order' => 5,
            ],
            [
                'category' => SystemSetting::CATEGORY_INTEREST_RATES,
                'key' => 'processing_fee_percentage',
                'label' => 'Processing Fee',
                'value' => '2',
                'default_value' => '2',
                'data_type' => 'number',
                'unit' => '% of loan',
                'description' => 'Processing fee as percentage of loan amount',
                'validation_rules' => json_encode(['min' => 0, 'max' => 10]),
                'is_public' => true,
                'display_order' => 6,
            ],
            [
                'category' => SystemSetting::CATEGORY_INTEREST_RATES,
                'key' => 'early_settlement_fee',
                'label' => 'Early Settlement Fee',
                'value' => '1',
                'default_value' => '1',
                'data_type' => 'number',
                'unit' => '% of outstanding',
                'description' => 'Fee for early loan settlement',
                'validation_rules' => json_encode(['min' => 0]),
                'is_public' => true,
                'display_order' => 7,
            ],

            // ========================================
            // ASSESSMENT PARAMETERS
            // ========================================
            [
                'category' => SystemSetting::CATEGORY_ASSESSMENT,
                'key' => 'min_bank_statement_months',
                'label' => 'Minimum Statement Period',
                'value' => '3',
                'default_value' => '3',
                'data_type' => 'number',
                'unit' => 'months',
                'description' => 'Minimum bank statement period required',
                'validation_rules' => json_encode(['min' => 1]),
                'is_public' => true,
                'display_order' => 1,
            ],
            [
                'category' => SystemSetting::CATEGORY_ASSESSMENT,
                'key' => 'max_cash_flow_volatility',
                'label' => 'Maximum Cash Flow Volatility',
                'value' => '50',
                'default_value' => '50',
                'data_type' => 'number',
                'unit' => '%',
                'description' => 'Maximum acceptable cash flow volatility',
                'validation_rules' => json_encode(['min' => 0, 'max' => 100]),
                'is_public' => false,
                'display_order' => 2,
            ],
            [
                'category' => SystemSetting::CATEGORY_ASSESSMENT,
                'key' => 'max_gambling_transactions_percentage',
                'label' => 'Max Gambling Transactions',
                'value' => '5',
                'default_value' => '5',
                'data_type' => 'number',
                'unit' => '% of expenses',
                'description' => 'Maximum acceptable gambling transactions as % of expenses',
                'validation_rules' => json_encode(['min' => 0, 'max' => 100]),
                'is_public' => false,
                'display_order' => 3,
            ],
            [
                'category' => SystemSetting::CATEGORY_ASSESSMENT,
                'key' => 'max_bounced_checks',
                'label' => 'Maximum Bounced Checks',
                'value' => '2',
                'default_value' => '2',
                'data_type' => 'number',
                'description' => 'Maximum number of bounced checks allowed',
                'validation_rules' => json_encode(['min' => 0]),
                'is_public' => false,
                'display_order' => 4,
            ],
            [
                'category' => SystemSetting::CATEGORY_ASSESSMENT,
                'key' => 'min_income_stability_score',
                'label' => 'Minimum Income Stability Score',
                'value' => '60',
                'default_value' => '60',
                'data_type' => 'number',
                'unit' => '%',
                'description' => 'Minimum income stability score required',
                'validation_rules' => json_encode(['min' => 0, 'max' => 100]),
                'is_public' => false,
                'display_order' => 5,
            ],
            [
                'category' => SystemSetting::CATEGORY_ASSESSMENT,
                'key' => 'stress_test_interest_increase',
                'label' => 'Stress Test Interest Increase',
                'value' => '3',
                'default_value' => '3',
                'data_type' => 'number',
                'unit' => '%',
                'description' => 'Interest rate increase for stress testing',
                'validation_rules' => json_encode(['min' => 0]),
                'is_public' => false,
                'display_order' => 6,
            ],
            [
                'category' => SystemSetting::CATEGORY_ASSESSMENT,
                'key' => 'stress_test_income_reduction',
                'label' => 'Stress Test Income Reduction',
                'value' => '20',
                'default_value' => '20',
                'data_type' => 'number',
                'unit' => '%',
                'description' => 'Income reduction percentage for stress testing',
                'validation_rules' => json_encode(['min' => 0, 'max' => 100]),
                'is_public' => false,
                'display_order' => 7,
            ],

            // ========================================
            // APPROVAL WORKFLOW
            // ========================================
            [
                'category' => SystemSetting::CATEGORY_WORKFLOW,
                'key' => 'approval_limit_level_1',
                'label' => 'Level 1 Approval Limit',
                'value' => '10000000',
                'default_value' => '10000000',
                'data_type' => 'number',
                'unit' => 'TZS',
                'description' => 'Maximum amount for Level 1 approval (Loan Officer)',
                'validation_rules' => json_encode(['min' => 0]),
                'is_public' => false,
                'display_order' => 1,
            ],
            [
                'category' => SystemSetting::CATEGORY_WORKFLOW,
                'key' => 'approval_limit_level_2',
                'label' => 'Level 2 Approval Limit',
                'value' => '50000000',
                'default_value' => '50000000',
                'data_type' => 'number',
                'unit' => 'TZS',
                'description' => 'Maximum amount for Level 2 approval (Branch Manager)',
                'validation_rules' => json_encode(['min' => 0]),
                'is_public' => false,
                'display_order' => 2,
            ],
            [
                'category' => SystemSetting::CATEGORY_WORKFLOW,
                'key' => 'approval_limit_level_3',
                'label' => 'Level 3 Approval Limit',
                'value' => '200000000',
                'default_value' => '200000000',
                'data_type' => 'number',
                'unit' => 'TZS',
                'description' => 'Maximum amount for Level 3 approval (Regional Manager)',
                'validation_rules' => json_encode(['min' => 0]),
                'is_public' => false,
                'display_order' => 3,
            ],
            [
                'category' => SystemSetting::CATEGORY_WORKFLOW,
                'key' => 'high_value_threshold',
                'label' => 'High Value Loan Threshold',
                'value' => '100000000',
                'default_value' => '100000000',
                'data_type' => 'number',
                'unit' => 'TZS',
                'description' => 'Threshold for high-value loans requiring special review',
                'validation_rules' => json_encode(['min' => 0]),
                'is_public' => false,
                'display_order' => 4,
            ],
            [
                'category' => SystemSetting::CATEGORY_WORKFLOW,
                'key' => 'maker_checker_enabled',
                'label' => 'Enable Maker-Checker',
                'value' => 'true',
                'default_value' => 'true',
                'data_type' => 'boolean',
                'description' => 'Enable maker-checker workflow for loan approvals',
                'is_public' => false,
                'display_order' => 5,
            ],
            [
                'category' => SystemSetting::CATEGORY_WORKFLOW,
                'key' => 'maker_checker_threshold',
                'label' => 'Maker-Checker Threshold',
                'value' => '20000000',
                'default_value' => '20000000',
                'data_type' => 'number',
                'unit' => 'TZS',
                'description' => 'Minimum loan amount requiring maker-checker',
                'validation_rules' => json_encode(['min' => 0]),
                'is_public' => false,
                'display_order' => 6,
            ],
            [
                'category' => SystemSetting::CATEGORY_WORKFLOW,
                'key' => 'auto_approval_enabled',
                'label' => 'Enable Auto-Approval',
                'value' => 'false',
                'default_value' => 'false',
                'data_type' => 'boolean',
                'description' => 'Enable automatic approval for qualifying loans',
                'is_public' => false,
                'display_order' => 7,
            ],
            [
                'category' => SystemSetting::CATEGORY_WORKFLOW,
                'key' => 'auto_approval_max_amount',
                'label' => 'Auto-Approval Max Amount',
                'value' => '5000000',
                'default_value' => '5000000',
                'data_type' => 'number',
                'unit' => 'TZS',
                'description' => 'Maximum amount for auto-approval',
                'validation_rules' => json_encode(['min' => 0]),
                'is_public' => false,
                'display_order' => 8,
            ],

            // ========================================
            // DOCUMENT REQUIREMENTS
            // ========================================
            [
                'category' => SystemSetting::CATEGORY_DOCUMENTS,
                'key' => 'id_document_required',
                'label' => 'ID Document Required',
                'value' => 'true',
                'default_value' => 'true',
                'data_type' => 'boolean',
                'description' => 'Require national ID or passport',
                'is_public' => true,
                'display_order' => 1,
            ],
            [
                'category' => SystemSetting::CATEGORY_DOCUMENTS,
                'key' => 'bank_statement_required',
                'label' => 'Bank Statement Required',
                'value' => 'true',
                'default_value' => 'true',
                'data_type' => 'boolean',
                'description' => 'Require bank statement for assessment',
                'is_public' => true,
                'display_order' => 2,
            ],
            [
                'category' => SystemSetting::CATEGORY_DOCUMENTS,
                'key' => 'income_proof_required',
                'label' => 'Income Proof Required',
                'value' => 'true',
                'default_value' => 'true',
                'data_type' => 'boolean',
                'description' => 'Require proof of income (payslip/tax returns)',
                'is_public' => true,
                'display_order' => 3,
            ],
            [
                'category' => SystemSetting::CATEGORY_DOCUMENTS,
                'key' => 'property_valuation_required',
                'label' => 'Property Valuation Required',
                'value' => 'true',
                'default_value' => 'true',
                'data_type' => 'boolean',
                'description' => 'Require professional property valuation',
                'is_public' => true,
                'display_order' => 4,
            ],
            [
                'category' => SystemSetting::CATEGORY_DOCUMENTS,
                'key' => 'document_validity_days',
                'label' => 'Document Validity Period',
                'value' => '90',
                'default_value' => '90',
                'data_type' => 'number',
                'unit' => 'days',
                'description' => 'Number of days documents remain valid',
                'validation_rules' => json_encode(['min' => 1]),
                'is_public' => false,
                'display_order' => 5,
            ],

            // ========================================
            // EMAIL TEMPLATES
            // ========================================
            [
                'category' => SystemSetting::CATEGORY_EMAILS,
                'key' => 'email_from_address',
                'label' => 'From Email Address',
                'value' => 'noreply@mortgage-platform.com',
                'default_value' => 'noreply@mortgage-platform.com',
                'data_type' => 'email',
                'description' => 'Default sender email address',
                'validation_rules' => json_encode(['email']),
                'is_public' => false,
                'display_order' => 1,
            ],
            [
                'category' => SystemSetting::CATEGORY_EMAILS,
                'key' => 'email_from_name',
                'label' => 'From Name',
                'value' => 'Mortgage Platform',
                'default_value' => 'Mortgage Platform',
                'data_type' => 'string',
                'description' => 'Default sender name',
                'is_public' => false,
                'display_order' => 2,
            ],
            [
                'category' => SystemSetting::CATEGORY_EMAILS,
                'key' => 'enable_email_notifications',
                'label' => 'Enable Email Notifications',
                'value' => 'true',
                'default_value' => 'true',
                'data_type' => 'boolean',
                'description' => 'Send email notifications to customers',
                'is_public' => false,
                'display_order' => 3,
            ],
            [
                'category' => SystemSetting::CATEGORY_EMAILS,
                'key' => 'application_received_template',
                'label' => 'Application Received Template',
                'value' => 'Dear {customer_name}, We have received your loan application #{application_number}. Our team will review it shortly.',
                'default_value' => 'Dear {customer_name}, We have received your loan application #{application_number}. Our team will review it shortly.',
                'data_type' => 'text',
                'description' => 'Template for application received email',
                'is_public' => false,
                'display_order' => 4,
            ],
            [
                'category' => SystemSetting::CATEGORY_EMAILS,
                'key' => 'application_approved_template',
                'label' => 'Application Approved Template',
                'value' => 'Congratulations {customer_name}! Your loan application #{application_number} for TZS {amount} has been approved.',
                'default_value' => 'Congratulations {customer_name}! Your loan application #{application_number} for TZS {amount} has been approved.',
                'data_type' => 'text',
                'description' => 'Template for application approval email',
                'is_public' => false,
                'display_order' => 5,
            ],
            [
                'category' => SystemSetting::CATEGORY_EMAILS,
                'key' => 'application_rejected_template',
                'label' => 'Application Rejected Template',
                'value' => 'Dear {customer_name}, We regret to inform you that your loan application #{application_number} could not be approved at this time. Reason: {reason}',
                'default_value' => 'Dear {customer_name}, We regret to inform you that your loan application #{application_number} could not be approved at this time. Reason: {reason}',
                'data_type' => 'text',
                'description' => 'Template for application rejection email',
                'is_public' => false,
                'display_order' => 6,
            ],

            // ========================================
            // BRANDING & APPEARANCE
            // ========================================
            [
                'category' => SystemSetting::CATEGORY_BRANDING,
                'key' => 'company_name',
                'label' => 'Company Name',
                'value' => 'White List Microfinance',
                'default_value' => 'White List Microfinance',
                'data_type' => 'string',
                'description' => 'Company name for reports and communications',
                'is_public' => true,
                'display_order' => 1,
            ],
            [
                'category' => SystemSetting::CATEGORY_BRANDING,
                'key' => 'company_logo_url',
                'label' => 'Company Logo URL',
                'value' => '/images/logo.png',
                'default_value' => '/images/logo.png',
                'data_type' => 'url',
                'description' => 'URL or path to company logo',
                'is_public' => true,
                'display_order' => 2,
            ],
            [
                'category' => SystemSetting::CATEGORY_BRANDING,
                'key' => 'primary_color',
                'label' => 'Primary Brand Color',
                'value' => '#2563eb',
                'default_value' => '#2563eb',
                'data_type' => 'color',
                'description' => 'Primary brand color (hex code)',
                'is_public' => true,
                'display_order' => 3,
            ],
            [
                'category' => SystemSetting::CATEGORY_BRANDING,
                'key' => 'secondary_color',
                'label' => 'Secondary Brand Color',
                'value' => '#1e40af',
                'default_value' => '#1e40af',
                'data_type' => 'color',
                'description' => 'Secondary brand color (hex code)',
                'is_public' => true,
                'display_order' => 4,
            ],
            [
                'category' => SystemSetting::CATEGORY_BRANDING,
                'key' => 'report_header_text',
                'label' => 'Report Header Text',
                'value' => 'White List Microfinance - Mortgage Platform',
                'default_value' => 'White List Microfinance - Mortgage Platform',
                'data_type' => 'string',
                'description' => 'Text displayed in report headers',
                'is_public' => false,
                'display_order' => 5,
            ],
            [
                'category' => SystemSetting::CATEGORY_BRANDING,
                'key' => 'report_footer_text',
                'label' => 'Report Footer Text',
                'value' => 'Confidential - For authorized use only',
                'default_value' => 'Confidential - For authorized use only',
                'data_type' => 'string',
                'description' => 'Text displayed in report footers',
                'is_public' => false,
                'display_order' => 6,
            ],

            // ========================================
            // SYSTEM CONFIGURATION
            // ========================================
            [
                'category' => SystemSetting::CATEGORY_SYSTEM,
                'key' => 'default_currency',
                'label' => 'Default Currency',
                'value' => 'TZS',
                'default_value' => 'TZS',
                'data_type' => 'string',
                'description' => 'Default currency code',
                'options' => json_encode(['TZS', 'USD', 'EUR', 'GBP']),
                'is_public' => true,
                'display_order' => 1,
            ],
            [
                'category' => SystemSetting::CATEGORY_SYSTEM,
                'key' => 'default_timezone',
                'label' => 'Default Timezone',
                'value' => 'Africa/Dar_es_Salaam',
                'default_value' => 'Africa/Dar_es_Salaam',
                'data_type' => 'string',
                'description' => 'Default timezone for the system',
                'is_public' => true,
                'display_order' => 2,
            ],
            [
                'category' => SystemSetting::CATEGORY_SYSTEM,
                'key' => 'date_format',
                'label' => 'Date Format',
                'value' => 'd M Y',
                'default_value' => 'd M Y',
                'data_type' => 'string',
                'description' => 'Date format (PHP format string)',
                'is_public' => true,
                'display_order' => 3,
            ],
            [
                'category' => SystemSetting::CATEGORY_SYSTEM,
                'key' => 'max_file_upload_size',
                'label' => 'Max File Upload Size',
                'value' => '10',
                'default_value' => '10',
                'data_type' => 'number',
                'unit' => 'MB',
                'description' => 'Maximum file size for uploads',
                'validation_rules' => json_encode(['min' => 1, 'max' => 100]),
                'is_public' => true,
                'display_order' => 4,
            ],
            [
                'category' => SystemSetting::CATEGORY_SYSTEM,
                'key' => 'session_timeout',
                'label' => 'Session Timeout',
                'value' => '120',
                'default_value' => '120',
                'data_type' => 'number',
                'unit' => 'minutes',
                'description' => 'User session timeout duration',
                'validation_rules' => json_encode(['min' => 1]),
                'is_public' => false,
                'display_order' => 5,
            ],
            [
                'category' => SystemSetting::CATEGORY_SYSTEM,
                'key' => 'enable_maintenance_mode',
                'label' => 'Maintenance Mode',
                'value' => 'false',
                'default_value' => 'false',
                'data_type' => 'boolean',
                'description' => 'Enable maintenance mode to restrict access',
                'is_public' => false,
                'display_order' => 6,
            ],

            // ========================================
            // INTEGRATIONS
            // ========================================
            [
                'category' => SystemSetting::CATEGORY_INTEGRATIONS,
                'key' => 'enable_sms_notifications',
                'label' => 'Enable SMS Notifications',
                'value' => 'false',
                'default_value' => 'false',
                'data_type' => 'boolean',
                'description' => 'Enable SMS notifications to customers',
                'is_public' => false,
                'display_order' => 1,
            ],
            [
                'category' => SystemSetting::CATEGORY_INTEGRATIONS,
                'key' => 'sms_provider',
                'label' => 'SMS Provider',
                'value' => '',
                'default_value' => '',
                'data_type' => 'string',
                'description' => 'SMS provider service name',
                'options' => json_encode(['twilio', 'nexmo', 'africas_talking']),
                'is_public' => false,
                'display_order' => 2,
            ],
            [
                'category' => SystemSetting::CATEGORY_INTEGRATIONS,
                'key' => 'sms_api_key',
                'label' => 'SMS API Key',
                'value' => '',
                'default_value' => '',
                'data_type' => 'string',
                'description' => 'API key for SMS provider (encrypted)',
                'is_public' => false,
                'is_editable' => true,
                'display_order' => 3,
            ],
            [
                'category' => SystemSetting::CATEGORY_INTEGRATIONS,
                'key' => 'payment_gateway_enabled',
                'label' => 'Payment Gateway Enabled',
                'value' => 'false',
                'default_value' => 'false',
                'data_type' => 'boolean',
                'description' => 'Enable payment gateway integration',
                'is_public' => false,
                'display_order' => 4,
            ],
            [
                'category' => SystemSetting::CATEGORY_INTEGRATIONS,
                'key' => 'payment_gateway_provider',
                'label' => 'Payment Gateway Provider',
                'value' => '',
                'default_value' => '',
                'data_type' => 'string',
                'description' => 'Payment gateway provider name',
                'options' => json_encode(['mpesa', 'tigopesa', 'airtel_money', 'stripe']),
                'is_public' => false,
                'display_order' => 5,
            ],
            [
                'category' => SystemSetting::CATEGORY_INTEGRATIONS,
                'key' => 'credit_bureau_enabled',
                'label' => 'Credit Bureau Integration',
                'value' => 'false',
                'default_value' => 'false',
                'data_type' => 'boolean',
                'description' => 'Enable credit bureau checks',
                'is_public' => false,
                'display_order' => 6,
            ],

            // ========================================
            // COMPLIANCE & AUDIT
            // ========================================
            [
                'category' => SystemSetting::CATEGORY_COMPLIANCE,
                'key' => 'enable_audit_log',
                'label' => 'Enable Audit Logging',
                'value' => 'true',
                'default_value' => 'true',
                'data_type' => 'boolean',
                'description' => 'Log all system actions for audit',
                'is_public' => false,
                'is_editable' => false,
                'display_order' => 1,
            ],
            [
                'category' => SystemSetting::CATEGORY_COMPLIANCE,
                'key' => 'data_retention_days',
                'label' => 'Data Retention Period',
                'value' => '2555',
                'default_value' => '2555',
                'data_type' => 'number',
                'unit' => 'days',
                'description' => 'Number of days to retain customer data (7 years)',
                'validation_rules' => json_encode(['min' => 1]),
                'is_public' => false,
                'display_order' => 2,
            ],
            [
                'category' => SystemSetting::CATEGORY_COMPLIANCE,
                'key' => 'gdpr_compliance_enabled',
                'label' => 'GDPR Compliance',
                'value' => 'true',
                'default_value' => 'true',
                'data_type' => 'boolean',
                'description' => 'Enable GDPR compliance features',
                'is_public' => false,
                'display_order' => 3,
            ],
            [
                'category' => SystemSetting::CATEGORY_COMPLIANCE,
                'key' => 'privacy_policy_url',
                'label' => 'Privacy Policy URL',
                'value' => '/privacy-policy',
                'default_value' => '/privacy-policy',
                'data_type' => 'url',
                'description' => 'URL to privacy policy page',
                'is_public' => true,
                'display_order' => 4,
            ],
            [
                'category' => SystemSetting::CATEGORY_COMPLIANCE,
                'key' => 'terms_of_service_url',
                'label' => 'Terms of Service URL',
                'value' => '/terms-of-service',
                'default_value' => '/terms-of-service',
                'data_type' => 'url',
                'description' => 'URL to terms of service page',
                'is_public' => true,
                'display_order' => 5,
            ],
            [
                'category' => SystemSetting::CATEGORY_COMPLIANCE,
                'key' => 'require_data_consent',
                'label' => 'Require Data Consent',
                'value' => 'true',
                'default_value' => 'true',
                'data_type' => 'boolean',
                'description' => 'Require explicit consent for data processing',
                'is_public' => true,
                'display_order' => 6,
            ],
        ];

        foreach ($settings as $setting) {
            SystemSetting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }

        $this->command->info('System settings seeded successfully!');
    }
}

